### ISSUE TITLE
Live Editor Broken in upcoming WordPress Version 5.2

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#749]
<img width="1045" alt="Screenshot 2019-04-05 at 17 55 43" src="https://user-images.githubusercontent.com/3070779/55643841-0c21d700-57cc-11e9-96b8-a4377fda8188.png">

**Comment by shramee** [comment]
Throws this error...
```
PHP Fatal error:  Uncaught Error: Call to undefined function get_available_post_mime_types() in /www/wp/ppb/wp-includes/media.php:3580
Stack trace:
#0 /www/wp/ppb/wp-content/plugins/pootle-page-builder/inc/live-editor/inc/class-public.php(153): wp_enqueue_media()
#1 /www/wp/ppb/wp-content/plugins/pootle-page-builder/inc/live-editor/inc/class-public.php(128): Pootle_Page_Builder_Live_Editor_Public->enqueue_scripts()
#2 /www/wp/ppb/wp-includes/class-wp-hook.php(286): Pootle_Page_Builder_Live_Editor_Public->enqueue('')
#3 /www/wp/ppb/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /www/wp/ppb/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /www/wp/ppb/wp-includes/script-loader.php(2535): do_action('wp_enqueue_scri...')
#6 /www/wp/ppb/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('')
#7 /www/wp/ppb/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#8 /www/wp/ppb/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#9 /www/wp/ppb/wp-includes/general-template.php( in /www/wp/ppb/wp-includes/media.php on line 3580
```
This is (probs) moved to `wp-admin/includes/post.php` and/or not included anymore.
